Estabelecimento/Estabelecimento/Models/Pessoa.cs
using NHibernate.Validator.Constraints;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Estabelecimento.Models
{
    public class Pessoa
    {
        public virtual int Id { get; set; }
        [NotNullNotEmpty]
        public virtual string Nome { get; set; }
        [NotNullNotEmpty]
        public virtual DateTime DataNascimento { get; set; }

    }
}

Estabelecimento/Estabelecimento/Models/Produto.cs
using NHibernate.Validator.Constraints;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Estabelecimento.Models
{
    public class Produto
    {
        public virtual int Id { get; set; }
        [NotNullNotEmpty]
        public virtual string Codigo { get; set; }
        [NotNullNotEmpty]
        public virtual string Nome { get; set; }
        [NotNullNotEmpty]
        public virtual double PrecoUnitario { get; set; }
    }
}

Estabelecimento/Estabelecimento/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Estabelecimento.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Estabelecimento/Estabelecimento/Controllers/PessoaController.cs
using Estabelecimento.Helpers;
using Estabelecimento.Models;
using NHibernate;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Estabelecimento.Controllers
{
    public class PessoaController : Controller
    {
        // GET: Pessoa
        public ActionResult Index()
        {
            using (ISession session = NHibernateHelper.OpenSession())
            {
                var pessoas = session.Query<Pessoa>().ToList();
                return View(pessoas);
            }
        }

        // GET: Pessoa/Details/5
        public ActionResult Details(int id)
        {
            using (ISession session = NHibernateHelper.OpenSession())
            {
                var pessoas = session.Get<Pessoa>(id);
                return View(pessoas);
            }
        }

        // GET: Pessoa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pessoa/Create
        [HttpPost]
        public ActionResult Create(Pessoa pessoa)
        {
            try
            {
                using (ISession session = NHibernateHelper.OpenSession())
                {
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Save(pessoa);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pessoa/Edit/5
        public ActionResult Edit(int id)
        {
            using (ISession session = NHibernateHelper.OpenSession())
            {
                var pessoas = session.Get<Pessoa>(id);
                return View(pessoas);
            }
        }

        // POST: Pessoa/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Pessoa pessoa)
        {
            try
            {
                using (ISession session = NHibernateHelper.OpenSession())
                {
                    var pessoaAlterada = session.Get<Pessoa>(id);
                    pessoaAlterada.Nome = pessoa.Nome;
                    pessoaAlterada.DataNascimento = pessoa.DataNascimento;
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Save(pessoaAlterada);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Pessoa/Delete/5
        public ActionResult Delete(int id)
        {
            using (ISession session = NHibernateHelper.OpenSession())
            {
                var pessoa = session.Get<Pessoa>(id);
                return View(pessoa);
            }
        }

        // POST: Pessoa/Delete/5
        [HttpPost]
        public ActionResult Delete(Pessoa pessoa)
        {
            try
            {
                using (ISession session = NHibernateHelper.OpenSession())
                {
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Delete(pessoa);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Estabelecimento/Estabelecimento/Controllers/ProdutoController.cs
using Estabelecimento.Helpers;
using Estabelecimento.Models;
using NHibernate;
using System.Linq;
using System.Web.Mvc;

namespace Estabelecimento.Controllers
{
    public class ProdutoController : Controller
    {
        // GET: Produto
        public ActionResult Index()
        {
            using (ISession session = NHibernateHelper.OpenSession())
            {
                var produtos = session.Query<Produto>().ToList();
                return View(produtos);
            }
        }

        // GET: Produto/Details/5
        public ActionResult Details(int id)
        {
            using (ISession session = NHibernateHelper.OpenSession())
            {
                var produtos = session.Get<Produto>(id);
                return View(produtos);
            }
        }

        // GET: Produto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produto/Create
        [HttpPost]
        public ActionResult Create(Produto produto)
        {
            try
            {
                using (ISession session = NHibernateHelper.OpenSession())
                {
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Save(produto);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Edit/5
        public ActionResult Edit(int id)
        {
            using (ISession session = NHibernateHelper.OpenSession())
            {
                var produto = session.Get<Produto>(id);
                return View(produto);
            }
        }

        // POST: Produto/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Produto produto)
        {
            try
            {
                using (ISession session = NHibernateHelper.OpenSession())
                {
                    var produtoAlterado = session.Get<Produto>(id);
                    produtoAlterado.Codigo = produto.Codigo;
                    produtoAlterado.Nome = produto.Nome;
                    produtoAlterado.PrecoUnitario = produto.PrecoUnitario;
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Save(produtoAlterado);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Produto/Delete/5
        public ActionResult Delete(int id)
        {
            using (ISession session = NHibernateHelper.OpenSession())
            {
                var produto = session.Get<Produto>(id);
                return View(produto);
            }
        }

        // POST: Produto/Delete/5
        [HttpPost]
        public ActionResult Delete(Produto produto)
        {
            try
            {
                using (ISession session = NHibernateHelper.OpenSession())
                {
                    using (ITransaction transaction = session.BeginTransaction())
                    {
                        session.Delete(produto);
                        transaction.Commit();
                    }
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Estabelecimento/Estabelecimento/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1 class="alert-success">Bem Vindo!</h1>

Estabelecimento/Estabelecimento/Views/Pessoa/Create.cshtml
@model Estabelecimento.Models.Pessoa

@{
    ViewBag.Title = "Nova Pessoa";
}

<h2>Criar Nova Pessoa</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Nome</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Data de Nascimento</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar Para Pessoas", "Index", null, new { @class = "btn btn-primary btn-large" })
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Estabelecimento/Estabelecimento/Views/Pessoa/Delete.cshtml
@model Estabelecimento.Models.Pessoa

@{
    ViewBag.Title = "Excluir Pessoa";
}



<h2 class="text-danger">Deseja realmente excluir esta pessoa?</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nome
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            Data de Nascimento
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-danger" />
            @Html.ActionLink("Voltar Para Pessoas", "Index", null, new { @class = "btn btn-primary btn-large" })
        </div>
    }
</div>

Estabelecimento/Estabelecimento/Views/Pessoa/Details.cshtml
@model Estabelecimento.Models.Pessoa

@{
    ViewBag.Title = "Detalhes da Pessoa";
}

<h2>Detalhes da Pessoa</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nome
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            Data de Nascimento
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Voltar Para Pessoas", "Index", null, new { @class = "btn btn-primary btn-large" })
</p>

Estabelecimento/Estabelecimento/Views/Pessoa/Edit.cshtml
@model Estabelecimento.Models.Pessoa

@{
    ViewBag.Title = "Editar Pessoa";
}

<h2>Editar Pessoa</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2">Nome</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Data de Nascimento</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar Para Pessoas", "Index", null, new { @class = "btn btn-primary btn-large" })
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Estabelecimento/Estabelecimento/Views/Pessoa/Index.cshtml
@model IEnumerable<Estabelecimento.Models.Pessoa>

@{
    ViewBag.Title = "Pessoas";
}

<h2>Pessoas</h2>

<p>
    @Html.ActionLink("Nova Pessoa", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Nome
        </th>
        <th>
            Data de Nascimento
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataNascimento)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.Id }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.Id }, new { @class = "text-danger" })
        </td>
    </tr>
}

</table>

Estabelecimento/Estabelecimento/Views/Produto/Create.cshtml
@model Estabelecimento.Models.Produto

@{
    ViewBag.Title = "Novo Produto";
}

<h2>Criar Novo Produto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class = "control-label col-md-2">Código</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nome</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Preço Unitário</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecoUnitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecoUnitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar Para Produtos", "Index", null, new { @class = "btn btn-primary btn-large" })
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Estabelecimento/Estabelecimento/Views/Produto/Delete.cshtml
@model Estabelecimento.Models.Produto

@{
    ViewBag.Title = "Excluir Produto";
}



<h2 class="text-danger">Deseja realmente excluir este produto?</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Código
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            Nome
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            Preço Unitário
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecoUnitario)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Excliur" class="btn btn-danger" /> 
        @Html.ActionLink("Voltar Para Produtos", "Index", null, new { @class = "btn btn-primary btn-large" })
    </div>
    }
</div>

Estabelecimento/Estabelecimento/Views/Produto/Details.cshtml
@model Estabelecimento.Models.Produto

@{
    ViewBag.Title = "Detalhes do Produto";
}

<h2>Detalhes do Produto</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Código
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            Nome
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            Preço Unitário
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecoUnitario)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary btn-large" })
    @Html.ActionLink("Voltar Para Produtos", "Index", null, new { @class = "btn btn-primary btn-large" })
</p>

Estabelecimento/Estabelecimento/Views/Produto/Edit.cshtml
@model Estabelecimento.Models.Produto

@{
    ViewBag.Title = "Editar Produto";
}

<h2>Editar Produto</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2">Código</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Nome</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Preço Unitário</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.PrecoUnitario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PrecoUnitario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Voltar Para Produtos", "Index", null, new { @class = "btn btn-primary btn-large" })
    </div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Estabelecimento/Estabelecimento/Views/Produto/Index.cshtml
@model IEnumerable<Estabelecimento.Models.Produto>

    @{
        ViewBag.Title = "Produtos";
    }

    <h2>Produtos</h2>

    <p>
        @Html.ActionLink("Novo Produto", "Create", null, new { @class = "btn btn-primary btn-large" })
    </p>
    <table class="table">
        <tr>
            <th>
                Código
            </th>
            <th>
                Nome
            </th>
            <th>
                Preço Unitário
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Codigo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrecoUnitario)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Excluir", "Delete", new { id = item.Id }, new { @class = "text-danger" })
                </td>
            </tr>
        }

    </table>

Estabelecimento/Estabelecimento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Estabelecimento", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Produtos", "Index", "Produto")</li>
                    <li>@Html.ActionLink("Pessoas", "Index", "Pessoa")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ben-Hur Lopes</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>